### ISSUE TITLE
Opening a new file via command line

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#132]
`python ci.py new_file_here` seems broken now. Here is the stack trace.

```
Traceback (most recent call last):
  File "/home/aaron/Desktop/open_source/ci_edit/app/background.py", line 61, in background
    program.focusedWindow.textBuffer.parseScreenMaybe()
  File "/home/aaron/Desktop/open_source/ci_edit/app/actions.py", line 1378, in parseScreenMaybe
    begin = min(len(self.parser.rows), self.upperChangedRow)
AttributeError: 'NoneType' object has no attribute 'rows'
```

**Comment by dschuyler** [comment]
Thanks!
Fixed with baa982b4be15e744c9deb15670d418b2d964cf70
