### ISSUE TITLE
Program crashed while editing (not sure of cause)

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#150]
Stack trace:

```
Traceback (most recent call last):
  File "/opt/ci_edit/app/background.py", line 82, in background
    redrawProgram(program, callerSemaphore)
  File "/opt/ci_edit/app/background.py", line 61, in redrawProgram
    program.render()
  File "/opt/ci_edit/app/ci_program.py", line 673, in render
    k.render()
  File "/opt/ci_edit/app/window.py", line 869, in render
    Window.render(self)
  File "/opt/ci_edit/app/window.py", line 254, in render
    self.textBuffer.draw(self)
  File "/opt/ci_edit/app/text_buffer.py", line 109, in draw
    self.drawTextArea(window, 0, 0, splitRow, cols, 0)
  File "/opt/ci_edit/app/text_buffer.py", line 198, in drawTextArea
    self.drawOverlays(window, top, left, rows, cols, colorDelta)
  File "/opt/ci_edit/app/text_buffer.py", line 273, in drawOverlays
    look[1](ch, look[0])
  File "/opt/ci_edit/app/text_buffer.py", line 249, in searchForward
    line = self.lines[row][textCol:]
IndexError: list index out of range
```

**Comment by dschuyler** [comment]
It looks like `row` somehow got to a higher value than the number of lines in the file. I've fixed similar bugs where lines were being deleted (or a block of text is cut). Do you have an idea of what may have been happening just before the crash?

**Comment by aaxu** [comment]
I'm not too sure. I think selected something or clicked with the mouse somewhere on the window and it crashed. I haven't been able to reproduce it though.

**Comment by aaxu** [comment]
This looks like it was due to #157. Closing since that is resolved.
