### ISSUE TITLE
curs_set() returned ERR

### ISSUE THREAD

**Issue by cup** [google/ci_edit#215]
Launching the program makes this happen:

~~~
Traceback (most recent call last):
  File "/Desktop/ci_edit-master/app/ci_program.py", line 557, in wrapped_ci
    prg.run()
  File "/Desktop/ci_edit-master/app/ci_program.py", line 494, in run
    self.commandLoop()
  File "/Desktop/ci_edit-master/app/ci_program.py", line 200, in commandLoop
    self.refresh(drawList, cursor, frameCmdCount)
  File "/Desktop/ci_edit-master/app/ci_program.py", line 433, in refresh
    curses.curs_set(0)  # Hide cursor.
_curses.error: curs_set() returned ERR
~~~

**Comment by nthparameter** [comment]
Thank you for reporting this. Could you tell us more about the computer this happened on?
I'm wondering which platform (Mac, Linux, Windows, etc.) it happened on.
Please also copy the output from running 
`we --version`
so we can see the version information.

**Comment by cup** [comment]
I dont use TUI editors currently. Good luck.
