### ISSUE TITLE
'm' index error

### ISSUE THREAD

**Issue by dschuyler** [google/ci_edit#22]
Not sure of full repro steps. I need to follow up on this.

info text_buffer.py 842 mouseRelease:  mouse release 10 0
detail mutator.py 355 undoOne: undo
detail mutator.py 409 undoOne: undo move
error ci_program.py 534 wrapped_ci: Traceback (most recent call last):
error ci_program.py 534 wrapped_ci:   File "/usr/local/google/home/dschuyler/github/ci_edit/app/ci_program.py", line 529, in wrapped_ci
    prg.run()
error ci_program.py 534 wrapped_ci:   File "/usr/local/google/home/dschuyler/github/ci_edit/app/ci_program.py", line 502, in run
    self.commandLoop()
error ci_program.py 534 wrapped_ci:   File "/usr/local/google/home/dschuyler/github/ci_edit/app/ci_program.py", line 97, in commandLoop
    self.refresh()
error ci_program.py 534 wrapped_ci:   File "/usr/local/google/home/dschuyler/github/ci_edit/app/ci_program.py", line 466, in refresh
    k.refresh()
error ci_program.py 534 wrapped_ci:   File "/usr/local/google/home/dschuyler/github/ci_edit/app/window.py", line 767, in refresh
    self.topInfo.onChange()
error ci_program.py 534 wrapped_ci:   File "/usr/local/google/home/dschuyler/github/ci_edit/app/window.py", line 555, in onChange
    if tb.isDirty():
error ci_program.py 534 wrapped_ci:   File "/usr/local/google/home/dschuyler/github/ci_edit/app/mutator.py", line 99, in isDirty
    self.redoChain[self.redoIndex][0] == 'm') or
error ci_program.py 534 wrapped_ci: IndexError: list index out of range

**Comment by dschuyler** [comment]
The PR from stasfilin lead me to a fix that has been landed.
