### ISSUE TITLE
_curses.error: setupterm: could not find terminfo database

### ISSUE THREAD

**Issue by Crabime** [google/ci_edit#67]
these days i have been always seeing ci_edit source code, everything is ok but i can not run it on pycharm. below is the error stacktrace when i ran Ci_program:
```PyDev console: starting.
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_run_in_console.py", line 71, in <module>
    globals = run_file(file, None, None)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_run_in_console.py", line 31, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/crabime/Development/PythonDevelopment/github/ci_edit/app/ci_program.py", line 611, in <module>
    run_ci()
  File "/Users/crabime/Development/PythonDevelopment/github/ci_edit/app/ci_program.py", line 602, in run_ci
    curses.wrapper(wrapped_ci)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/curses/wrapper.py", line 22, in wrapper
    stdscr = curses.initscr()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/curses/__init__.py", line 33, in initscr
    fd=_sys.__stdout__.fileno())
_curses.error: setupterm: could not find terminfo database
```

**I had tried these ways:**
- add `TERM=xterm-256color ` and `TERMINFO=/usr/share/terminfo/78` in path which located in `~/.bash_profile`，that doesn't work, such error still appear
- **add such environment variables into pycharm program run/debug configuration directly,**still doesn't work.

so far, i have tried all the way but still can not debug curses program. and here is the [link](https://stackoverflow.com/questions/45951125/osx-curses-error-setupterm-could-not-find-terminfo-database) to the question i putted forward in stackoverflow but still nobody knows,hope someone can save me out.

Current OS version: OS X 10.11.4
System Platform: Darwin

**Comment by dschuyler** [comment]
I'm not sure, but I'll try to help:

Maybe try running a different ncurses program in pycharm to see if it's particular to ci_edit or running ncurses programs in pycharm.

You may also be able to use ci_edit/test_fake/curses if rendering to the screen is not needed. The test_fake/curses is something I wrote to use the unittest framework with ci_edit. It has an API that is similar to curses, but the calls are "fake". They don't really open windows or draw text.

**Comment by Crabime** [comment]
thanks for your response although waiting for long. and I had tried run a
really simple curses program in pycharm, it still can not run whose error
still like above, only if i run it in mac terminal then it can work well.

2017年9月16日 上午11:19，"Dave Schuyler" <notifications@github.com>写道：
